services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        - KAGGLE_API_TOKEN=${KAGGLE_API_TOKEN}
    image: ghcr.io/excoffierleonard/kaggle-competitions:latest
    environment:
      KAGGLE_API_TOKEN: ${KAGGLE_API_TOKEN}
      PRESETS: ${PRESETS:-}
      TIME_LIMIT: ${TIME_LIMIT:-}
      SUBMIT: ${SUBMIT:-}