[project]
name = "kaggle-competitions"
version = "0.1.0"
description = "Code for Kaggle Competitions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogluon>=1.5.0",
    "kaggle>=1.8.3",
]
