[project]
name = "kagglecomp-pgs06e01"
version = "0.1.0"
description = "Code for Kaggle Competition: Playground Series - Season 6 Episode 1 - Predicting Student Test Scores"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogluon>=1.5.0",
    "kaggle>=1.8.3",
]
